# MEMO: 入門!実践!サーバーサイドKotlinで紹介されていたDocker構成を参考に実装しています
# (URL) https://booth.pm/ja/items/1560389

# 実行手順:
# $ docker-compose up -d
# $ chmod +x make_database.sh
# $ sh make_database.sh

version: '3'
services: 
  db:
    image: mysql:5.7 
    # M1またはM2のMacの場合にはplatform指定`linux/amd64`を追加すること。
    # ※IntelMacの場合はなくても良い。
    platform: linux/amd64
    container_name: visual_effect_sample_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: visual_effect_sample_database
      MYSQL_USER: just1factory
      MYSQL_PASSWORD: just1factory
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      # MEMO: 初期データ投入用やTest環境用のDB作成が必要な場合を想定している
      - ./docker/db/sql:/docker-initdb
    ports:
      - 3306:3306