# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'VisualEffectTraceExample' do
  use_frameworks!

  # Pods for VisualEffectTraceExample

  # 1. アーキテクチャに関するライブラリ
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RealmSwift'
  pod 'KeychainAccess'
  pod 'Kingfisher'

  # 2. UI実装に関するライブラリ
  pod 'BouncyLayout'
  pod 'FontAwesome.swift'
  pod 'PKHUD', '~> 5.0'
  pod 'AnimatedCollectionViewLayout'

  # 3. UIデバッグ用のライブラリ
  pod 'Gedatsu', configuration: %w(Debug)

  # ※ ユニットテスト時に利用する
  target 'VisualEffectTraceExampleTests' do
    inherit! :search_paths
    pod 'RxBlocking'
    pod 'RxTest'
    pod 'SwiftyMocky'
    pod 'Nimble'
    pod 'Quick'
  end

  # ※ UIテスト時に利用する
  target 'VisualEffectTraceExampleUITests' do
    # Do Nothing.
  end
end

#  ※ Team IDを追加する対応（Xcode14から必要になった処理）
# post_install do |installer|
#   installer.generated_projects.each do |project|
#     project.targets.each do |target|
#       target.build_configurations.each do |config|
#         config.build_settings["DEVELOPMENT_TEAM"] = "S5BF5553KY"
#       end
#     end
#   end
# end

