# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VisualEffectTraceExample' do
  use_frameworks!

  # Pods for VisualEffectTraceExample

  # 1. アーキテクチャに関するライブラリ
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'ReSwift'
  pod 'RealmSwift'
  pod 'KeychainAccess'
  pod 'Kingfisher'

  # 2. UI実装に関するライブラリ
  pod 'BouncyLayout'
  pod 'FontAwesome.swift'
  pod 'PKHUD', '~> 5.0'
  pod 'AnimatedCollectionViewLayout'

  # 3. UIデバッグ用のライブラリ
  pod 'Gedatsu', configuration: %w(Debug)

#  ※ ユニットテスト時に利用する
#  target 'VisualEffectTraceExampleTests' do
#    inherit! :search_paths
#  end
#  ※ UIテスト時に利用する
#  target 'VisualEffectTraceExampleUITests' do
#  end
end
