# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VisualEffectTraceExample' do
  use_frameworks!

  # Pods for VisualEffectTraceExample

  # 1. アーキテクチャに関するライブラリ
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'ReSwift'
  pod 'RealmSwift'
  pod 'KeychainAccess'
  pod 'DifferenceKit'
  
  # 2. UI実装に関するライブラリ
  pod 'ESTabBarController-swift'
  pod 'PanModal'
  pod 'AirBar'
  pod 'YPImagePicker'
  pod 'ExpandingMenu', '~> 0.4'
  pod 'Loaf'
  pod 'NVActivityIndicatorView'
  pod 'AnimatedCollectionViewLayout'
  pod 'Nuke'

#  ※ ユニットテスト時に利用する
#  target 'VisualEffectTraceExampleTests' do
#    inherit! :search_paths
#  end
#  ※ UIテスト時に利用する
#  target 'VisualEffectTraceExampleUITests' do
#  end
end
